# yamllint disable rule:line-length
---
stages:
  - lint
  - build
  - image
  - deploy

#  These variables below are always reqiured to get buildah working at specific
# at liu and should always be here. Do not remove
variables:
  _BUILDAH_STARTED_IN_USERNS: ""
  BUILDAH_ISOLATION: chroot
  STORAGE_DRIVER: vfs
  BUILDAH_FORMAT: docker

#Here we can insert tests for this iteration unless we are already using a test
# framework

#Linting aka making sure yaml and yml syntax is correct
yamllint:
  stage: lint
  needs: []
  image: pipelinecomponents/yamllint
  allow_failure: false # Change to true if you want to treat failure as a warning
  script:
    - yamllint ./k8

#Here we are building a docker image of our back end and pushing it to our internal
#registry
image-rdx-backend:
  # Please make sure you keep the `variables` section of this file if you want
  # to reuse this pipeline step for something else
  stage: image
  image: docker.io/buildah/buildah
  only:
     - master
     - main
     - dev
     - Fixfordeployment
  # needs:
  #   - test-backend

  script:
    # Set up our build
    - cd Web
    - export DIR= "Web"
    - export NAME="rdx-backend"

    - buildah build-using-dockerfile --tag "${NAME}" "${DIR}"
    - buildah push --creds "${CI_REGISTRY_USER}:${CI_JOB_TOKEN}" "${NAME}" "docker://${CI_REGISTRY_IMAGE}/${NAME}:latest" && exit 0 || true
    - buildah push --creds "${CI_REGISTRY_USER}:${CI_JOB_TOKEN}" "${NAME}" "docker://${CI_REGISTRY_IMAGE}/${NAME}:latest"

deploy-test-k8s-connection:
  stage: deploy
  image: bitnami/kubectl
  needs: []
  only:
    - Fixfordeployment
    - master
    - main
    - dev
  script:
    - kubectl get all
deploy-k8s-regcred:
  stage: deploy
  image: bitnami/kubectl
  needs:
    - deploy-test-k8s-connection
  only:
    - Fixfordeployment
    - master
    - main
    - dev
  script:
    - kubectl get secrets | grep liu-gitlab-regcred && exit 0
    - kubectl create secret docker-registry liu-gitlab-regcred --docker-server=https://gitlab.liu.se:5000 --docker-username=k8s --docker-password=${REGISTRY_PASSWORD}
    - kubectl get secret liu-gitlab-regcred

# Deploy our application to k8s!
deploy-rdx-backend:
  stage: deploy
  image: bitnami/kubectl

  # Only deploy when on main/master/dev
  only:
    - Fixfordeployment
    - master
    - main
    - dev
  # And wait for all dependencies to build
  needs:
    - deploy-test-k8s-connection
    - deploy-k8s-regcred
    - image-rdx-backend
    - yamllint
  script:
    - kubectl apply -f k8/backend.yaml
    - kubectl rollout restart deployment rdx-backend-app-deployment
  
